[package]
name = "pact"
version = "0.3.1" # updated dependencies
edition = "2024"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.27", features = ["derive"] }
html-escape = "0.2.13"
rayon = "1.10.0"
ureq = "3.0.5"
